In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/cars.csv")
df.sample(5)

       brand  km_driven    fuel         owner  selling_price
3771  Maruti      67000  Diesel  Second Owner         450000
4398    Tata      53000  Diesel   First Owner         980000
6337     BMW      50000  Diesel   First Owner        1000000
1413  Maruti      30000  Petrol   First Owner         335000
3169    Tata      63000  Diesel   First Owner         445000

In [9]:
pd.get_dummies(df ,columns = ['fuel','owner'] ,drop_first= True ,) #temporary not in place

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [22]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
ohe = OneHotEncoder(drop='first')
encoded_array = ohe.fit_transform(df[['fuel', 'owner']]).toarray()
encoded_df = pd.DataFrame(encoded_array, columns=ohe.get_feature_names_out(['fuel', 'owner']))
final_df = pd.concat([df[['brand', 'km_driven']].reset_index(drop=True), encoded_df], axis=1)
final_df

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Skoda,120000,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,Honda,140000,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,Hyundai,127000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Maruti,120000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8124,Hyundai,119000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
8125,Maruti,120000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8126,Tata,25000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8127,Tata,25000,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
counts = final_df['brand'].value_counts()
threshold = 100
repl = counts[counts<=threshold].index
lis = pd.get_dummies(final_df['brand'].replace(repl,'uncommon'))
pd.concat([lis, df['km_driven'].reset_index(drop=True), encoded_df], axis=1)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,...,Volkswagen,uncommon,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,False,False,False,False,False,False,True,False,False,False,...,False,False,145500,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,False,False,False,False,False,False,False,False,True,False,...,False,False,120000,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,False,False,False,True,False,False,False,False,False,False,...,False,False,140000,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,False,False,False,False,True,False,False,False,False,False,...,False,False,127000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,False,False,False,False,False,False,True,False,False,False,...,False,False,120000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,...,False,False,110000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8124,False,False,False,False,True,False,False,False,False,False,...,False,False,119000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
8125,False,False,False,False,False,False,True,False,False,False,...,False,False,120000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8126,False,False,False,False,False,False,False,False,False,True,...,False,False,25000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8127,False,False,False,False,False,False,False,False,False,True,...,False,False,25000,1.0,0.0,0.0,0.0,0.0,0.0,0.0

array([['Maruti', 145500, 1.0, ..., 0.0, 0.0, 0.0],
       ['Skoda', 120000, 1.0, ..., 1.0, 0.0, 0.0],
       ['Honda', 140000, 0.0, ..., 0.0, 0.0, 1.0],
       ...,
       ['Maruti', 120000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 25000, 1.0, ..., 0.0, 0.0, 0.0]], dtype=object)